add the image input field. (#27)
Yassa-hue/graduation-project-flutter pull request #41
Opened 2024-05-19 16:59 UTC by ihab4real

issues: #27 

![image](https://github.com/Yassa-hue/graduation-project-flutter/assets/71561048/b42b1262-63f0-468d-84ab-8b841588bc88)

2024-05-20 06:16 UTC, Yassa-hue requested changes
I don't like the UX of this section:

![image](https://github.com/Yassa-hue/graduation-project-flutter/assets/58339464/2a7e68ed-becf-454f-a66e-dff04980f28a)


The icon on the top and then the image section looks off.

Here are two suggestions (you can pick any, it's up to you):
* Move the image widget to the bottom of the screen.
* Change the shape of the image to be a rectangle like the other input fields.

2024-05-20 06:16 UTC, Yassa-hue commented on lib/pages/user_form_page.dart
> +  File? campaignImage;
campaignImage !! WTF ?!

2024-06-04 16:53 UTC, ihab4real commented on lib/pages/user_form_page.dart
> +  File? campaignImage;
anything else? (really thought?)

2024-06-04 17:10 UTC, ihab4real commented
> * Move the image widget to the bottom of the screen.

i did this one. it got even weirder. but we need the round thing to give the user a preview of the image after being cropped.

2024-06-04 17:16 UTC, Yassa-hue commented on lib/pages/user_form_page.dart
> +  File? campaignImage;
userProfileImage ?

2024-06-05 05:57 UTC, Yassa-hue commented
As discussed on the DM, use the layout that I proposed and merge.
@ihab4real

2024-06-05 15:21 UTC, closed without merging